export interface BackendConfig {
  id: string;
  name: string;
  skillsPath: string;
  commandsPath: string | null;
  commandSyntax: "colon" | "hyphen" | "bare" | "skill";
  fileExtension: ".md" | ".prompt" | ".prompt.md" | ".toml" | null;
  supportsCommands: boolean;
  supportsSkills: boolean;
  globalHomeEnv?: string;
  fallbackGlobalPath?: string;
  note?: string;
  minVersion?: string;
  testedVersions?: string[];
}

export const BACKENDS: BackendConfig[] = [
  {
    id: "claude",
    name: "Claude Code",
    skillsPath: ".claude/skills",
    commandsPath: ".claude/commands",
    commandSyntax: "colon",
    fileExtension: ".md",
    supportsCommands: true,
    supportsSkills: true,
  },
  {
    id: "cursor",
    name: "Cursor",
    skillsPath: ".cursor/skills",
    commandsPath: ".cursor/commands",
    commandSyntax: "hyphen",
    fileExtension: ".md",
    supportsCommands: true,
    supportsSkills: true,
  },
  {
    id: "codex",
    name: "OpenAI Codex CLI",
    skillsPath: ".codex/skills",
    commandsPath: "prompts",
    commandSyntax: "colon",
    fileExtension: ".md",
    supportsCommands: true,
    supportsSkills: true,
    globalHomeEnv: "CODEX_HOME",
    fallbackGlobalPath: "~/.codex/prompts",
    note: "Commands written to $CODEX_HOME/prompts (global path)",
  },
  {
    id: "github-copilot",
    name: "GitHub Copilot",
    skillsPath: ".github/copilot/skills",
    commandsPath: ".github/copilot/commands",
    commandSyntax: "hyphen",
    fileExtension: ".prompt.md",
    supportsCommands: true,
    supportsSkills: true,
    note: "Commands require IDE extension (VS Code, JetBrains, Visual Studio)",
  },
  {
    id: "kiro",
    name: "Kiro",
    skillsPath: ".kiro/skills",
    commandsPath: ".kiro/commands",
    commandSyntax: "hyphen",
    fileExtension: ".prompt.md",
    supportsCommands: true,
    supportsSkills: true,
  },
  {
    id: "gemini",
    name: "Gemini CLI",
    skillsPath: ".gemini/skills",
    commandsPath: ".gemini/commands",
    commandSyntax: "bare",
    fileExtension: ".toml",
    supportsCommands: true,
    supportsSkills: true,
  },
  {
    id: "opendev",
    name: "OpenDev",
    skillsPath: ".opendev/skills",
    commandsPath: ".opendev/commands",
    commandSyntax: "colon",
    fileExtension: ".md",
    supportsCommands: true,
    supportsSkills: true,
  },
  {
    id: "generic",
    name: "Generic",
    skillsPath: ".generic/skills",
    commandsPath: ".generic/commands",
    commandSyntax: "colon",
    fileExtension: ".md",
    supportsCommands: true,
    supportsSkills: true,
  },
  {
    id: "pi",
    name: "Pi",
    skillsPath: ".pi/skills",
    commandsPath: ".pi/commands",
    commandSyntax: "colon",
    fileExtension: ".md",
    supportsCommands: true,
    supportsSkills: true,
  },
  {
    id: "antigravity",
    name: "Antigravity",
    skillsPath: ".antigravity/skills",
    commandsPath: ".antigravity/commands",
    commandSyntax: "colon",
    fileExtension: ".md",
    supportsCommands: true,
    supportsSkills: true,
  },
  {
    id: "amazon-q",
    name: "Amazon Q Developer",
    skillsPath: ".amazonq/skills",
    commandsPath: ".amazonq/commands",
    commandSyntax: "colon",
    fileExtension: ".md",
    supportsCommands: true,
    supportsSkills: true,
  },
  {
    id: "auggie",
    name: "Auggie",
    skillsPath: ".auggie/skills",
    commandsPath: ".auggie/commands",
    commandSyntax: "colon",
    fileExtension: ".md",
    supportsCommands: true,
    supportsSkills: true,
  },
  {
    id: "bob",
    name: "Bob",
    skillsPath: ".bob/skills",
    commandsPath: ".bob/commands",
    commandSyntax: "colon",
    fileExtension: ".md",
    supportsCommands: true,
    supportsSkills: true,
  },
  {
    id: "cline",
    name: "Cline",
    skillsPath: ".cline/workflows/skills",
    commandsPath: ".cline/workflows/commands",
    commandSyntax: "hyphen",
    fileExtension: ".md",
    supportsCommands: true,
    supportsSkills: true,
  },
  {
    id: "codebuddy",
    name: "CodeBuddy",
    skillsPath: ".codebuddy/.opsx/skills",
    commandsPath: ".codebuddy/.opsx/commands",
    commandSyntax: "colon",
    fileExtension: ".md",
    supportsCommands: true,
    supportsSkills: true,
  },
  {
    id: "continue",
    name: "Continue",
    skillsPath: ".continue/skills",
    commandsPath: ".continue/commands",
    commandSyntax: "hyphen",
    fileExtension: ".prompt",
    supportsCommands: true,
    supportsSkills: true,
  },
  {
    id: "costrict",
    name: "Costrict",
    skillsPath: ".costrict/config/opsx/skills",
    commandsPath: ".costrict/config/opsx/commands",
    commandSyntax: "bare",
    fileExtension: ".md",
    supportsCommands: true,
    supportsSkills: true,
  },
  {
    id: "crush",
    name: "Crush",
    skillsPath: ".crush/.opsx/skills",
    commandsPath: ".crush/.opsx/commands",
    commandSyntax: "colon",
    fileExtension: ".md",
    supportsCommands: true,
    supportsSkills: true,
  },
  {
    id: "factory",
    name: "Factory",
    skillsPath: ".factory/skills",
    commandsPath: ".factory/commands",
    commandSyntax: "colon",
    fileExtension: ".md",
    supportsCommands: true,
    supportsSkills: true,
  },
  {
    id: "forgecode",
    name: "Forge Code",
    skillsPath: ".forgecode/skills",
    commandsPath: null,
    commandSyntax: "skill",
    fileExtension: null,
    supportsCommands: false,
    supportsSkills: true,
    note: "Skill-only backend — no command files generated",
  },
  {
    id: "iflow",
    name: "iFlow",
    skillsPath: ".iflow/skills",
    commandsPath: ".iflow/commands",
    commandSyntax: "colon",
    fileExtension: ".md",
    supportsCommands: true,
    supportsSkills: true,
  },
  {
    id: "junie",
    name: "Junie",
    skillsPath: ".junie/skills",
    commandsPath: ".junie/commands",
    commandSyntax: "colon",
    fileExtension: ".md",
    supportsCommands: true,
    supportsSkills: true,
  },
  {
    id: "kilocode",
    name: "Kilo Code",
    skillsPath: ".kilocode/workflows/skills",
    commandsPath: ".kilocode/workflows/commands",
    commandSyntax: "hyphen",
    fileExtension: ".md",
    supportsCommands: true,
    supportsSkills: true,
  },
  {
    id: "kimi",
    name: "Kimi",
    skillsPath: ".kimi/skills",
    commandsPath: null,
    commandSyntax: "skill",
    fileExtension: null,
    supportsCommands: false,
    supportsSkills: true,
    note: "Skill-only backend — no command files generated",
  },
  {
    id: "lingma",
    name: "Lingma",
    skillsPath: ".lingma/.opsx/skills",
    commandsPath: ".lingma/.opsx/commands",
    commandSyntax: "colon",
    fileExtension: ".md",
    supportsCommands: true,
    supportsSkills: true,
  },
  {
    id: "opencode",
    name: "OpenCode",
    skillsPath: ".opencode/skills",
    commandsPath: ".opencode/commands",
    commandSyntax: "colon",
    fileExtension: ".md",
    supportsCommands: true,
    supportsSkills: true,
  },
  {
    id: "qoder",
    name: "Qoder",
    skillsPath: ".qoder/.opsx/skills",
    commandsPath: ".qoder/.opsx/commands",
    commandSyntax: "colon",
    fileExtension: ".md",
    supportsCommands: true,
    supportsSkills: true,
  },
  {
    id: "qwen",
    name: "Qwen",
    skillsPath: ".qwen/skills",
    commandsPath: ".qwen/commands",
    commandSyntax: "bare",
    fileExtension: ".toml",
    supportsCommands: true,
    supportsSkills: true,
  },
  {
    id: "roocode",
    name: "Roo Code",
    skillsPath: ".roocode/skills",
    commandsPath: ".roocode/commands",
    commandSyntax: "colon",
    fileExtension: ".md",
    supportsCommands: true,
    supportsSkills: true,
  },
  {
    id: "trae",
    name: "Trae",
    skillsPath: ".trae/skills",
    commandsPath: null,
    commandSyntax: "bare",
    fileExtension: null,
    supportsCommands: false,
    supportsSkills: true,
    note: "Skill-only backend — no command files generated",
  },
  {
    id: "windsurf",
    name: "Windsurf",
    skillsPath: ".windsurf/workflows/skills",
    commandsPath: ".windsurf/workflows/commands",
    commandSyntax: "hyphen",
    fileExtension: ".md",
    supportsCommands: true,
    supportsSkills: true,
  },
] as const;

export function getBackend(id: string): BackendConfig {
  const backend = BACKENDS.find((b) => b.id === id);
  if (!backend) {
    throw new Error(`Unknown backend: "${id}". Valid IDs: ${listBackendIds().join(", ")}`);
  }
  return backend;
}

export function listBackendIds(): string[] {
  return BACKENDS.map((b) => b.id);
}

export function getSkillOnlyBackends(): BackendConfig[] {
  return BACKENDS.filter((b) => !b.supportsCommands);
}
