import * as fs from "node:fs";
import * as path from "node:path";
import chalk from "chalk";
import { Command } from "commander";
import ora from "ora";
import { loadProjectConfig } from "../../config/project.js";
import { loadUserConfig } from "../../config/user.js";
import { detect } from "../../detector/index.js";
import { resolveTemplatePack } from "../../templater/selector.js";
import { EXIT_CODES } from "../../validator/index.js";

interface DocumentationFiles {
  governance: string;
  skills: string;
  agents: string;
  compliance?: string;
}

function generateGovernanceDoc(ir: any): string {
  const rules = ir.rules || [];

  const rulesTable =
    rules.length > 0
      ? `| ID | Scope | Severity | Action |\n|---|---|---|---|\n${rules
          .map(
            (r: any) =>
              `| ${r.id || "—"} | \`${r.scope || "**/*"}\` | ${r.severity || "—"} | ${(r.action || "").substring(0, 50)}... |`
          )
          .join("\n")}`
      : "No rules defined.";

  return `# Governance Rules

## Summary

${rules.length} rule(s) defined.

## Rules Table

${rulesTable}

${
  ir.meta?.conflict_resolution
    ? `## Conflict Resolution

\`\`\`json
${JSON.stringify(ir.meta.conflict_resolution, null, 2)}
\`\`\``
    : ""
}

Generated by open-blueprint.
`;
}

function generateSkillsDoc(ir: any): string {
  const skills = ir.skills || [];

  const skillsList =
    skills.length > 0
      ? skills
          .map(
            (s: any) =>
              `### ${s.name || "Unnamed Skill"}

${s.description || "_No description_"}

**When to use:** ${s.when_to_use || "Not specified"}

**Required tools:** ${(s.tools_required || []).join(", ") || "_None_"}

**Procedure:**
\`\`\`
${s.procedure || "Not specified"}
\`\`\`
`
          )
          .join("\n\n")
      : "No skills defined.";

  return `# Skills Catalog

## Summary

${skills.length} skill(s) defined.

## Skills

${skillsList}

Generated by open-blueprint.
`;
}

function generateAgentsDoc(ir: any): string {
  const personas = ir.personas || [];

  const agentsList =
    personas.length > 0
      ? personas
          .map(
            (p: any) =>
              `### ${p.name || "Unnamed Agent"}

**Role:** ${p.role || "_Unspecified_"}

**Reasoning:** ${p.reasoning_style || "Not specified"}

**Constraints:** ${(p.constraints || []).join("; ") || "None"}

**Allowed Tools:** ${(p.allowed_tools || []).join(", ") || "Not restricted"}
`
          )
          .join("\n\n")
      : "No agents/personas defined.";

  return `# Agent Definitions

## Summary

${personas.length} agent(s) defined.

## Agents

${agentsList}

Generated by open-blueprint.
`;
}

function generateComplianceDoc(ir: any): string {
  const compliance = ir.compliance || {};
  const frameworks = compliance.frameworks || {};

  const frameworksList = Object.entries(frameworks)
    .map(
      ([name, status]) =>
        `- **${name.toUpperCase()}**: ${status ? "✓ Mapped" : "✗ Not mapped"}`
    )
    .join("\n");

  return `# Compliance Checklist

## Frameworks

${frameworksList || "No frameworks defined."}

${
  compliance.gaps
    ? `## Gaps

${(compliance.gaps || []).map((g: string) => `- ${g}`).join("\n")}`
    : ""
}

${
  compliance.certified
    ? `## Certification Status

Certified: **${compliance.certified}**`
    : ""
}

Generated by open-blueprint.
`;
}

export function createDocsCommand(): Command {
  const cmd = new Command("docs");

  cmd
    .description("Generate governance documentation from blueprint")
    .option("--output <path>", "Output directory (default: ./blueprint-docs)", "./blueprint-docs")
    .action(async (opts: { output: string }) => {
      const cwd = process.cwd();
      const projectConfig = loadProjectConfig(cwd);
      const userConfig = loadUserConfig();
      const backend = projectConfig?.backend ?? userConfig.default_backend;
      const outputDir = path.resolve(opts.output);

      if (!fs.existsSync(outputDir)) {
        fs.mkdirSync(outputDir, { recursive: true });
      }

      const spinner = ora({ text: "Generating documentation...", color: "cyan" }).start();

      try {
        const fingerprint = await detect(cwd);
        const pack = resolveTemplatePack(fingerprint, backend as any);

        // For now, use a simplified IR structure.
        // In a full implementation, this would parse the actual blueprint files.
        const ir: Record<string, any> = {
          rules: [] as Array<Record<string, any>>,
          skills: [] as Array<Record<string, any>>,
          personas: [] as Array<Record<string, any>>,
          compliance: {},
          meta: {},
        };

        // Parse .claude/rules/*.md files
        const rulesDir = path.join(cwd, ".claude", "rules");
        if (fs.existsSync(rulesDir)) {
          const ruleFiles = fs
            .readdirSync(rulesDir)
            .filter((f) => f.endsWith(".md"));
          for (const file of ruleFiles) {
            const filePath = path.join(rulesDir, file);
            const content = fs.readFileSync(filePath, "utf-8");
            const match = content.match(/^---\n([\s\S]*?)\n---/);
            if (match) {
              try {
                // Parse YAML frontmatter (simplified)
                const yamlBlock = match[1] ?? "";
                const rule: any = { id: file.replace(".md", "") };
                const scopeMatch = yamlBlock.match(/scope:\s*"?([^"\n]+)"?/);
                const severityMatch = yamlBlock.match(/severity:\s*(\w+)/);
                const actionMatch = yamlBlock.match(/action:\s*"([^"]*)"/);
                if (scopeMatch?.[1]) rule.scope = scopeMatch[1];
                if (severityMatch?.[1]) rule.severity = severityMatch[1];
                if (actionMatch?.[1]) rule.action = actionMatch[1];
                ir.rules.push(rule);
              } catch {
                /* Ignore parse errors */
              }
            }
          }
        }

        // Parse .claude/skills/*.md files
        const skillsDir = path.join(cwd, ".claude", "skills");
        if (fs.existsSync(skillsDir)) {
          const skillFiles = fs
            .readdirSync(skillsDir)
            .filter((f) => f.endsWith(".md"));
          for (const file of skillFiles) {
            const filePath = path.join(skillsDir, file);
            const content = fs.readFileSync(filePath, "utf-8");
            const match = content.match(/^---\n([\s\S]*?)\n---/);
            if (match) {
              try {
                const yamlBlock = match[1] ?? "";
                const skill: any = {};
                const nameMatch = yamlBlock.match(/name:\s*"?([^"\n]+)"?/);
                const descMatch = yamlBlock.match(
                  /description:\s*"?([^"\n]+)"?/
                );
                if (nameMatch?.[1]) skill.name = nameMatch[1];
                if (descMatch?.[1]) skill.description = descMatch[1];
                ir.skills.push(skill);
              } catch {
                /* Ignore parse errors */
              }
            }
          }
        }

        // Generate docs
        const docs: DocumentationFiles = {
          governance: generateGovernanceDoc(ir),
          skills: generateSkillsDoc(ir),
          agents: generateAgentsDoc(ir),
        };

        if (Object.keys(ir.compliance).length > 0) {
          docs.compliance = generateComplianceDoc(ir);
        }

        // Write files
        fs.writeFileSync(path.join(outputDir, "GOVERNANCE.md"), docs.governance, "utf-8");
        fs.writeFileSync(path.join(outputDir, "SKILLS.md"), docs.skills, "utf-8");
        fs.writeFileSync(path.join(outputDir, "AGENTS.md"), docs.agents, "utf-8");
        if (docs.compliance) {
          fs.writeFileSync(
            path.join(outputDir, "COMPLIANCE.md"),
            docs.compliance,
            "utf-8"
          );
        }

        spinner.succeed(chalk.green("Documentation generated!"));

        console.log(chalk.cyan(`\nGenerated files:`));
        console.log(chalk.cyan(`  ✔ GOVERNANCE.md`));
        console.log(chalk.cyan(`  ✔ SKILLS.md`));
        console.log(chalk.cyan(`  ✔ AGENTS.md`));
        if (docs.compliance) {
          console.log(chalk.cyan(`  ✔ COMPLIANCE.md`));
        }

        console.log(
          chalk.dim(
            `\nOutput: ${path.relative(cwd, outputDir)}`
          )
        );
      } catch (e) {
        spinner.fail(chalk.red(`Documentation generation failed: ${e instanceof Error ? e.message : String(e)}`));
        process.exit(EXIT_CODES.GENERAL_ERROR);
      }
    });

  return cmd;
}
